name: deployment
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Get the code
        uses: actions/checkout@v3
      - name: intall dependencies
        run: npn ci
      - name: lint
        run: npm run lint
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: intall dependencies
        run: npn ci
      - name: test
        run: npm run test
