name: firstghaction
on: [push, workflow_dispatch]
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: set up job 
        run: echo "setting up job"
      - name: install eslint
        run: npm install -g eslint
      - name: list directory contents
        run: ls -la
      - name: lint 
        run: eslint --ext .jsx --fix ../../src
      - name: test
        run: vitest run
      
